# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn gatsby-cli
    - run: yarn install --frozen-lockfile
    - run: yarn run lint
    - run: yarn run test --runInBand --no-cache
      env:
        CI: true
    - run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
    - run: gatsby build
    - uses: amondnet/now-deployment@v2
      with:
        zeit-token: ${{ secrets.ZEIT_TOKEN }} # Required
        now-args: '--prod' #Optional
        now-org-id: ${{ secrets.ORG_ID}}  #Required
        now-project-id: ${{ secrets.PROJECT_ID}} #Required
        working-directory: ./